import { Aliases } from "./types";

export const ru: Aliases = {
    "screen size": "размер экрана",
    "screen resolution": "разрешение экрана",
    "built-in memory": "встроенная память",
    "ram memory": "оперативная память",
    contrast: "контрастность",
    diagonal: "диагональ экрана",
    "contrast ratio": "контраст",
    "refresh rate": "частота обновления",
    "total power": "суммарная мощность",
    "bluetooth profiles": "профили Bluetooth",
    "usb socket": "разъем USB",
    "max resolution": "максимальное разрешение",
    "processor type": "тип процессора",
    "flash memory": "встроенная flash память",
    "total ouput": "суммарная выходная мощность",
    "subwoofer output": "выходная мощность сабвуфера",
    "dolby digital": "поддержка Dolby Digital",
    frequency: "частотный диапазон",
    "connection type": "тип подключения",
    "wire length": "длина провода",
    "screen ferequency": "частота обновления экрана",
    "usb port amount": "количество портов USB",
    "power supply": "питание",
    weight: "вес",
    socket: "сокет",
    chipset: "чипсет",
    "memory type": "тип памяти",
    "video memory capacity": "объем видеопамяти",
    "video memory type": "тип видеопамяти",
    "video memory bus capacity": "разрядность шины видеопамяти",
    "video resolution": "разрешение видео",
    "video recording": "запись видео",
    "viewing angle": "угол обзора",
    "noise reduction rating": "чувствительность динамика",
    "microphone fixation": "крепление микрофона",
};